# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = lib.mkForce [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"

    # Previous opions before custom kernel-config
    # "atkbd"
    # "autofs"
    # "efivarfs"
    # "ehci_hcd"
    # "ehci_pci"
    # "ext2"
    # "ext4"
    # "hid_apple"
    # "hid_cherry"
    # "hid_corsair"
    # "hid_generic"
    # "hid_lenovo"
    # "hid_logitech_dj"
    # "hid_logitech_hidpp"
    # "hid_microsoft"
    # "hid_roccat"
    # "i8042"
    # "mmc_block"
    # "nvme"
    # "ohci_hcd"
    # "ohci_pci"
    # "pata_marvell"
    # "pcips2"
    # "rtsx_pci_sdmmc"
    # "sata_nv"
    # "sata_sis"
    # "sata_uli"
    # "sata_via"
    # "sd_mod"
    # "sr_mod"
    # "thunderbolt"
    # "tpm-crb"
    # "tpm-tis"
    # "uhci_hcd"
    # "usb_storage"
    # "usbhid"
    # "vmd"
    # "xhci_hcd"
    # "xhci_pci"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1009cf1c-ffe3-4aba-a5d3-1de55e7e7063";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/86A0-3217";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
