[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
# WARNING: Matugen needs to be compiled with the `update-informer` feature for this to work.
version_check = false

# Enables caching which will cache the colorscheme, custom colors, etc. into a cache folder located in
# Windows: C:\Users\user\AppData\Roaming\InioX\matugen\cache\images\<file>
# Linux: $XDG_CACHE_HOME/matugen/<file> or $HOME/.cache/matugen/images/<file>
# MacOS: $HOME/Library/Caches/matugen/images/<file>
# The file follows this naming: <image_name>.<image_extension>.<image_hash>.json
# For example: testimage.png.0cfd2d624b3d09bf6246b7be9ca79e207e7aa1189d961d44949628b99811bb9d.json
# You can modify the cache and it will then be loaded when using the same image.
caching = true

# Changing the syntax
# Expr is for stuff like for loops etc.
expr_prefix = ['<', '*']
expr_postfix = ['*', '>']

# Block is for keywords like {{ <keyword> }}
block_prefix = ['{', '{']
block_postfix = ['}', '}']

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.tofi]
input_path = '~/.config/matugen/templates/tofi-config'
output_path = '~/.config/tofi/config'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-config.kdl'
output_path = '~/.config/niri/config.kdl'

[templates.eww]
input_path = '~/.config/matugen/templates/_eww-colors.scss'
output_path = '~/.config/eww/_eww-colors.scss'
